default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  encoding: unicode

development:
  <<: *default
  database: groupath_development
  username: pguser
  password: postgres

test:
  <<: *default
  database: groupath_test
  username: pguser
  password: postgres

production:
  <<: *default
  database: groupath_production
  username: groupath
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
